//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public class DynamicTextClickableObject : ClickableObject
{
	public string[] messages;
	
	public override void OnClicked (Vector2 mouse)
	{
		BeenClicked = true;
		
		float x = transform.position.x;
		float y = transform.position.y;
		
		DialogController.Instance.objectRect = new Rect (Screen.width / 3 + x * 2 , Screen.height * 1 / 4 - y, Screen.width / 4, Screen.height / 4);
		DialogController.Instance.SendMessage("DynamicMessage", messages);
		
		
	}
	
	protected override void ChildAwake()
	{
		foreach (string s in messages)
			if (s == ""){
				messages[0] = "Object Message Missing!";
			}
	}
	
}