//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public class StaticTextClickableObject : ClickableObject
{
	public string message;

	public override void OnClicked (Vector2 mouse)
	{
		float x = transform.position.x;
		float y = transform.position.y;

		DialogController.Instance.objectRect = new Rect (Screen.width / 3 + x * 2 , Screen.height * 1 / 4 - y, Screen.width / 4, Screen.height / 4);
		DialogController.Instance.SendMessage("StaticMessage", message);
	}

	protected override void ChildAwake()
	{
		if (message == null){
			message = "Object Message Missing!";
		}
	}

}